### ISSUE TITLE
Error while building in gradle plugin:4.1.0 and gradle version:6.5

### ISSUE THREAD

**Issue by aarjan** [ayyshim/esewa_pnp#7] opened 2020-11-12 04:59 UTC
The app is not building after upgrading Gradle.

Execution failed for task ':esewa_pnp:bundleDebugAar'.                  
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :esewa_pnp project caused this error: ~/.pub-cache/hosted/pub.dartlang.org/esewa_pnp-1.0.0/android/libs/eSewaSdk.aar

**Comment by ayyshim** [comment] 2020-12-08 16:42
I tried to reproduce the error by creating a new flutter project and adding esewa_pnp plugin in it but I didn't get the error you've mentioned. Can you help me reproduce this error?

**Comment by ayyshim** [comment] 2020-12-16 13:53
I am closing this issue, marking it Unclear because you couldn't present the method to reproduce the issue.

**Closed by ayyshim** 2020-12-16 13:53 UTC
Labels: Unclear

**Comment by aarjan** [comment] 2021-01-22 06:37
Can you test it by upgrading gradle in following files,
android/build.gradle 
```classpath 'com.android.tools.build:gradle:4.1.1'```

android/gradle/wrapper/gradle-wrapper.properties
```distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip```

**Comment by Abhishek-Khanal** [comment] 2021-02-19 15:22
Current solution is to downgrade the android gradle version to 3.x.x
